// <auto-generated />
using Acosta.AssetTracking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Acosta.AssetTracking.Data.Migrations
{
    [DbContext(typeof(AssetContext))]
    partial class AssetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Acosta.AssetTracking.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetTypeId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Manufacturer")
                        .IsRequired();

                    b.Property<string>("Model");

                    b.Property<string>("SerialNumber")
                        .IsRequired();

                    b.Property<string>("TagNumber")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Assets");

                    b.HasData(
                        new { Id = 1, AssetTypeId = 2, Description = "24 inch monitor", Manufacturer = "Dell", Model = "XPS", SerialNumber = "123JDH1", TagNumber = "100a" },
                        new { Id = 2, AssetTypeId = 2, Description = "32 inch curved monitor", Manufacturer = "HP", Model = "Omen", SerialNumber = "HDU2830", TagNumber = "200a" },
                        new { Id = 3, AssetTypeId = 3, Description = "10inch smartphone", Manufacturer = "Acer", Model = "XPHONE", SerialNumber = "93CFHS9", TagNumber = "300SE8" },
                        new { Id = 4, AssetTypeId = 1, Description = "Best destop computer yet", Manufacturer = "Dell", Model = "Monster", SerialNumber = "927CNE9", TagNumber = "KSIV8" },
                        new { Id = 5, AssetTypeId = 1, Description = "Best selling computer", Manufacturer = "Acer", Model = "Core Pro", SerialNumber = "93CFHS9", TagNumber = "KDIC7" }
                    );
                });

            modelBuilder.Entity("Acosta.AssetTracking.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new { Id = 1, Name = "Desktop Computer" },
                        new { Id = 2, Name = "Monitor" },
                        new { Id = 3, Name = "Phone" }
                    );
                });

            modelBuilder.Entity("Acosta.AssetTracking.Domain.Asset", b =>
                {
                    b.HasOne("Acosta.AssetTracking.Domain.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
